# Generated by Django 3.1.4 on 2021-04-26 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='anonymous',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='匿名用户'),
        ),
        migrations.AddField(
            model_name='solution',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
    ]
