# Generated by Django 3.1.4 on 2021-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210426_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.CharField(default=1, max_length=8, verbose_name='题目序号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='问卷描述'),
        ),
    ]
