# Generated by Django 3.1.4 on 2021-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210428_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='prompt',
            field=models.CharField(default='', max_length=128, verbose_name='提示问题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyuser',
            name='reply',
            field=models.CharField(default='', max_length=128, verbose_name='提示问题答案'),
            preserve_default=False,
        ),
    ]
